Config file handling
kruchone/jambi pull request #11
Opened 2016-10-25 22:31 UTC by fvox13

2016-10-27 16:02 UTC, kruchone commented
Looks like this fix has changes from the other PR. Could you revert the config file changes from this one?

2016-10-27 16:48 UTC, fvox13 commented
I think I may have done the PR incorrectly.  Is it possible to just exclude the first commit when you merge?

2016-10-27 18:18 UTC, kruchone commented
Potentially doing a `git revert 9ec8562` and `git revert c355208` on that branch would undo the two commits. I can't even merge it because it is conflicting with the last PR that was merged (because we would be merging the same one twice). Since this is on your fork, I would have to check out your branch on your fork and modify it. Let me know how you want to proceed, I can commit into your branch if it works better for you.

Also, if you could make the spacing consistent with jambi.py in config.py that would be good (although at some point I will re-run flake8 and fix spacing anyway).

2016-10-27 18:32 UTC, kruchone requested changes

2016-10-27 18:32 UTC, kruchone commented on jambi/config.py
> +				"install directory, or set the {} environment variable." \
Potentially confusing to people who might not know what the 'install directory' is. Maybe alternative wording would be something like. "[...]Either create jambi.conf in _this_ directory[...]"

What do you think?

Edit: In fact, we could just remove the bit "in the install directory"

2016-10-27 18:32 UTC, kruchone commented on jambi/config.py
> +ENVIRONMENT_VARIABLE = "JAMBI_CONFIG"
Is the value in this ENV variable relative or absolute? I can see usage either way, but was leaning toward absolute path. What are your thoughts?

2016-10-27 18:35 UTC, kruchone commented
I would like to see an extra `argparse` option `--config` that allows someone to point to a [relative or absolute] path to a config file to use as `jambi.conf`, even if it isn't named `jambi.conf`.

If you want that to be handled separately I am happy to do it, just thought I would mention here as we are dealing with configgy things :)

2016-10-28 01:10 UTC, fvox13 commented on jambi/config.py
> +ENVIRONMENT_VARIABLE = "JAMBI_CONFIG"
Absolute.  It just gets passed to the config parser as-is, assuming we can verify it's a file.

2016-10-28 01:11 UTC, fvox13 commented on jambi/config.py
> +				"install directory, or set the {} environment variable." \
Yeah, it's also kind of weird to put a config file in your site-packages directory, now that I think through it...

2016-10-28 02:06 UTC, fvox13 commented
Recommend closing this PR in favor of #12

2016-10-28 02:06 UTC, closed without merging